spring:
  config:
    import: "optional:configserver:"
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/test_realm
  cloud:
    config:
      discovery:
        serviceId: config-server
        enabled: true
    gateway:
      default-filters:
        - TokenRelay=
      routes:
      - id: checkout-service
        uri: lb://checkout-service
        predicates:
        - Path=/checkout
        filters:
          - AddRequestHeader=X-Request-from, gateway
          - AddResponseHeader=X-Response-res, done
server:
  port: 9000